import { useState, useEffect, useMemo } from 'react'
import {
  ArrowLeft,
  FileText,
  ZoomOut,
  ZoomIn,
  Maximize,
  Minimize,
  Share2,
  Download,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Check,
  Loader2,
  X,
  Plus,
  AlertCircle
} from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { Button } from '@/components/ui/Button'
import { Card, CardContent } from '@/components/ui/Card'
import { Avatar } from '@/components/ui/Avatar'
import { Modal } from '@/components/ui/Modal'
import { documentService, type DocumentResponse } from '@/services/documentService'
import { useTranslation } from '@/context/LanguageContext'

export function FilePreviewPage() {
  const { t, language } = useTranslation()
  const [searchParams] = useSearchParams()
  const docId = searchParams.get('id')

  const [document, setDocument] = useState<DocumentResponse | null>(null)
  const [previewText, setPreviewText] = useState<string>('')
  const [imageUrl, setImageUrl] = useState<string>('')
  const [pdfUrl, setPdfUrl] = useState<string>('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const [zoom, setZoom] = useState(100)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const [currentPage, setCurrentPage] = useState(1)
  const [isDownloading, setIsDownloading] = useState(false)
  const [isDownloaded, setIsDownloaded] = useState(false)
  const [isShareModalOpen, setIsShareModalOpen] = useState(false)
  const [isLinkCopied, setIsLinkCopied] = useState(false)
  const [tags, setTags] = useState(['Study Material'])
  const [newTag, setNewTag] = useState('')
  const [isAddingTag, setIsAddingTag] = useState(false)

  useEffect(() => {
    if (!docId) {
      setError('Không tìm thấy tài liệu yêu cầu (No document ID specified)')
      setLoading(false)
      return
    }

    const loadDocument = async () => {
      try {
        setLoading(true)
        setError(null)
        const doc = await documentService.getDocumentById(docId)
        setDocument(doc)

        const ext = (doc.originalFileName || doc.fileName).split('.').pop()?.toLowerCase() || ''
        const isImg = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'].includes(ext)
        const isPdf = ext === 'pdf'

        if (isImg) {
          const blob = await documentService.downloadDocument(docId)
          const url = URL.createObjectURL(blob)
          setImageUrl(url)
        } else if (isPdf) {
          const blob = await documentService.downloadDocument(docId)
          const url = URL.createObjectURL(blob)
          setPdfUrl(url)
        } else {
          try {
            const text = await documentService.previewDocument(docId)
            setPreviewText(text || '')
          } catch (err) {
            console.warn('No text preview available for this document:', err)
            setPreviewText('')
          }
        }
      } catch (err) {
        console.error('Failed to load document preview:', err)
        setError('Không thể tải thông tin tệp tin này hoặc tệp không tồn tại.')
      } finally {
        setLoading(false)
      }
    }

    loadDocument()
  }, [docId])

  // Clean up object URLs when component unmounts
  useEffect(() => {
    return () => {
      if (imageUrl) {
        URL.revokeObjectURL(imageUrl)
      }
      if (pdfUrl) {
        URL.revokeObjectURL(pdfUrl)
      }
    }
  }, [imageUrl, pdfUrl])

  const pages = useMemo(() => {
    if (!previewText) return []
    // Split by Form Feed character commonly generated by PDFTextStripper
    const splitPages = previewText.split('\f')
    const filtered = splitPages.map((p) => p.trim()).filter(Boolean)
    return filtered.length > 0 ? filtered : [previewText]
  }, [previewText])

  const totalPages = useMemo(() => {
    if (imageUrl || pdfUrl) return 1
    return pages.length || 1
  }, [imageUrl, pdfUrl, pages])

  // Reset page number when totalPages changes
  useEffect(() => {
    setCurrentPage(1)
  }, [totalPages])

  const pageContent = pages[currentPage - 1] || ''

  const handleZoomIn = () => setZoom((prev) => Math.min(prev + 10, 150))
  const handleZoomOut = () => setZoom((prev) => Math.max(prev - 10, 50))

  const handlePrevPage = () => setCurrentPage((prev) => Math.max(prev - 1, 1))
  const handleNextPage = () => setCurrentPage((prev) => Math.min(prev + 1, totalPages))

  const handleDownload = async () => {
    if (!docId || !document) return
    setIsDownloading(true)
    try {
      const blob = await documentService.downloadDocument(docId)
      const url = URL.createObjectURL(blob)
      const a = window.document.createElement('a')
      a.href = url
      a.download = document.originalFileName || document.fileName
      window.document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)
      setIsDownloaded(true)
      setTimeout(() => setIsDownloaded(false), 3000)
    } catch (err) {
      console.error('Failed to download document:', err)
    } finally {
      setIsDownloading(false)
    }
  }

  const handleShare = () => {
    setIsShareModalOpen(true)
  }

  const handleRemoveTag = (tagToRemove: string) => {
    setTags((prev) => prev.filter((t) => t !== tagToRemove))
  }

  const handleAddTag = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      const trimmed = newTag.trim()
      if (trimmed !== '' && !tags.includes(trimmed)) {
        setTags([...tags, trimmed])
      }
      setNewTag('')
      setIsAddingTag(false)
    } else if (e.key === 'Escape') {
      setNewTag('')
      setIsAddingTag(false)
    }
  }

  const formatSize = (bytes: number) => {
    if (!bytes) return '0 B'
    const k = 1024
    const sizes = ['B', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i]
  }

  const formatUploadedDate = (dateStr?: string) => {
    if (!dateStr) return ''
    try {
      return new Date(dateStr).toLocaleDateString(language === 'vi' ? 'vi-VN' : 'en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
    } catch {
      return dateStr
    }
  }

  const fileExtension = useMemo(() => {
    if (!document) return ''
    return (document.originalFileName || document.fileName).split('.').pop()?.toUpperCase() || ''
  }, [document])

  const shareLinkValue = useMemo(() => {
    if (!document) return ''
    return `${window.location.origin}/api/documents/${document.id}/download`
  }, [document])

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] gap-3">
        <Loader2 className="size-10 animate-spin text-primary" />
        <span className="text-sm font-semibold text-muted">Đang tải thông tin tài liệu...</span>
      </div>
    )
  }

  if (error || !document) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] gap-4 max-w-md mx-auto text-center">
        <AlertCircle className="size-12 text-destructive" />
        <h3 className="text-lg font-bold text-foreground">{error || 'Không tìm thấy tài liệu'}</h3>
        <p className="text-muted text-sm">
          Tài liệu bạn yêu cầu không khả dụng, đã bị xóa hoặc bạn không có quyền truy cập.
        </p>
        <Link to="/dashboard/storage/explorer">
          <Button variant="primary" className="bg-[#3155F6] hover:bg-[#2563eb] text-white">
            Quay lại Explorer
          </Button>
        </Link>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6 w-full max-w-6xl mx-auto pb-10">
      {/* Header */}
      <div>
        <Link 
          to="/dashboard/storage/explorer" 
          className="inline-flex items-center gap-2 text-sm font-medium text-muted hover:text-foreground mb-4 transition-colors"
        >
          <ArrowLeft className="size-4" />
          {t.filePreview.backToExplorer}
        </Link>
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
          <div>
            <h1 className="text-[32px] font-bold text-foreground leading-tight">{document.title}</h1>
            <p className="text-muted mt-2 text-sm">
              {document.originalFileName || document.fileName}
            </p>
          </div>
          <div className="flex gap-3">
            <Button 
              onClick={handleShare}
              variant="secondary" 
              className="gap-2 h-9 px-4 text-sm font-medium transition-colors shadow-sm text-[#3155F6] border-slate-200 hover:bg-slate-50 bg-white"
            >
              <Share2 className="size-4" />
              {t.filePreview.shareAccess}
            </Button>
            <Button 
              onClick={handleDownload}
              disabled={isDownloading}
              className={`gap-2 h-9 px-4 text-sm font-medium transition-colors shadow-sm ${
                isDownloaded
                  ? 'bg-emerald-600 hover:bg-emerald-700 text-white'
                  : 'bg-[#3155F6] hover:bg-[#2563eb] text-white'
              }`}
            >
              {isDownloading ? (
                <Loader2 className="size-4 animate-spin" />
              ) : isDownloaded ? (
                <Check className="size-4" />
              ) : (
                <Download className="size-4" />
              )}
              {isDownloading ? t.filePreview.downloading : isDownloaded ? t.filePreview.downloaded : t.filePreview.downloadPdf}
            </Button>
          </div>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 items-start">
        {/* Left Viewer */}
        <div className={isFullscreen ? "fixed inset-0 z-50 bg-[#f8fafc] dark:bg-slate-950 flex flex-col w-full h-full" : "flex-1 flex flex-col w-full"}>
          {pdfUrl ? (
            // Native PDF Viewer using iframe on Blob URL
            <div className="border border-border dark:border-slate-800 rounded-xl overflow-hidden w-full bg-white dark:bg-slate-900 min-h-[700px] h-[750px] shadow-sm">
              <iframe
                src={pdfUrl}
                className="w-full h-full border-none"
                title={document.title}
              />
            </div>
          ) : (
            <>
              {/* Viewer Toolbar */}
              <div className={`h-12 bg-white dark:bg-slate-900 border-border dark:border-slate-800 flex items-center justify-between px-4 ${isFullscreen ? 'border-b' : 'border rounded-t-xl'}`}>
                <div className="flex items-center gap-2">
                  <FileText className="size-4 text-[#ef4444]" />
                  <span className="text-sm font-semibold text-foreground truncate max-w-[150px] sm:max-w-none">
                    {document.originalFileName || document.fileName}
                  </span>
                </div>
                <div className="flex items-center gap-4 text-muted text-sm font-medium">
                  <div className="hidden sm:flex items-center gap-3">
                    <button onClick={handleZoomOut} className="hover:text-foreground transition-colors p-1" title={t.fileViewer.zoomOut}><ZoomOut className="size-4" /></button>
                    <span className="w-12 text-center select-none">{zoom}%</span>
                    <button onClick={handleZoomIn} className="hover:text-foreground transition-colors p-1" title={t.fileViewer.zoomIn}><ZoomIn className="size-4" /></button>
                  </div>
                  <div className="hidden sm:block w-px h-4 bg-border dark:bg-slate-800"></div>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={handlePrevPage} 
                      disabled={currentPage === 1}
                      className="hover:text-foreground disabled:opacity-50 transition-colors p-1"
                    >
                      <ChevronLeft className="size-4" />
                    </button>
                    <span className="select-none min-w-[70px] text-center">
                      {t.filePreview.pageText(currentPage, totalPages)}
                    </span>
                    <button 
                      onClick={handleNextPage} 
                      disabled={currentPage === totalPages}
                      className="hover:text-foreground disabled:opacity-50 transition-colors p-1"
                    >
                      <ChevronRight className="size-4" />
                    </button>
                  </div>
                  <div className="hidden sm:block w-px h-4 bg-border dark:bg-slate-800"></div>
                  <button onClick={() => setIsFullscreen(!isFullscreen)} className="hover:text-foreground transition-colors p-1 hidden sm:block" title={t.fileViewer.fullscreenViewer}>
                    {isFullscreen ? <Minimize className="size-4" /> : <Maximize className="size-4" />}
                  </button>
                </div>
              </div>
              
              {/* Document Content */}
              <div className={`bg-[#f8fafc] dark:bg-slate-950 border-border dark:border-slate-800 p-4 sm:p-8 flex justify-center overflow-auto ${isFullscreen ? 'flex-1' : 'border border-t-0 rounded-b-xl min-h-[600px]'}`}>
                {imageUrl ? (
                  // Image Preview
                  <div className="flex items-center justify-center p-4 min-h-[500px]">
                    <img 
                      src={imageUrl} 
                      alt={document.title} 
                      style={{ transform: `scale(${zoom / 100})`, transition: 'transform 0.1s ease' }} 
                      className="max-h-[600px] object-contain shadow-md rounded-lg" 
                    />
                  </div>
                ) : pageContent ? (
                  // Text Preview Content
                  <div 
                    className="bg-white dark:bg-slate-900 w-full max-w-[600px] shadow-sm border border-border dark:border-slate-800 p-6 sm:p-10 flex flex-col h-fit transition-all duration-200"
                    style={{ zoom: `${zoom}%` } as React.CSSProperties}
                  >
                    <h2 className="text-2xl sm:text-[28px] font-bold leading-tight text-[#1e293b] dark:text-white mb-2">
                      {document.title}
                    </h2>
                    <div className="flex justify-between items-center mb-6 mt-2">
                      <p className="text-[#3b82f6] text-[11px] font-bold tracking-widest uppercase">{document.originalFileName || document.fileName}</p>
                      <span className="text-[11px] text-muted font-bold bg-slate-100 dark:bg-slate-800 px-2 py-1 rounded">
                        {t.fileViewer.page} {currentPage} / {totalPages}
                      </span>
                    </div>
                    <div className="whitespace-pre-wrap text-sm text-slate-700 dark:text-slate-350 leading-relaxed font-sans">
                      {pageContent}
                    </div>
                  </div>
                ) : (
                  // No preview support template (e.g. word doc, zip, empty files)
                  <div className="flex flex-col items-center justify-center py-20 px-4 text-center min-h-[500px] w-full">
                    <FileText className="size-16 text-muted-foreground mb-4" />
                    <h3 className="text-lg font-bold text-foreground mb-2">{document.title}</h3>
                    <p className="text-muted text-sm max-w-sm mb-6">
                      {language === 'vi' 
                        ? 'Không có bản xem trước trực tuyến cho loại tệp này. Bạn có thể tải tệp tin về thiết bị để xem.'
                        : 'No online preview is available for this file type. You can still download the file to view it on your device.'
                      }
                    </p>
                    <Button onClick={handleDownload} className="bg-[#3155F6] hover:bg-[#2563eb] text-white gap-2 h-10 px-6 font-semibold">
                      <Download className="size-4" />
                      {language === 'vi' ? 'Tải tệp tin xuống' : 'Download File'}
                    </Button>
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {/* Right Details Panel */}
        <Card className="w-full lg:w-[320px] shrink-0 border-border dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm lg:sticky lg:top-6">
          <CardContent className="p-6">
            <h3 className="font-bold text-foreground text-lg mb-6">{t.filePreview.fileDetails}</h3>
            
            <div className="flex flex-col gap-5 mb-8">
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted font-medium">{t.filePreview.type}</span>
                <span className="text-[10px] font-bold bg-[#e5eeff] dark:bg-blue-950/40 text-[#2563eb] dark:text-blue-400 px-2 py-1 rounded">
                  {fileExtension}
                </span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted font-medium">{t.filePreview.size}</span>
                <span className="font-semibold text-foreground text-right">{formatSize(document.fileSize)}</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted font-medium">{t.filePreview.uploaded}</span>
                <span className="font-semibold text-foreground text-right">{formatUploadedDate(document.createdAt)}</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-muted font-medium">{t.filePreview.owner}</span>
                <div className="flex items-center gap-2">
                  <Avatar src="/logo.png" name="Owner" className="size-6 border border-border dark:border-slate-800" />
                  <span className="font-semibold text-foreground">
                    {document.userId === Number(searchParams.get('userId')) || document.userId === 5 ? t.filePreview.you : 'User #' + document.userId}
                  </span>
                </div>
              </div>
            </div>

            <div>
              <h4 className="text-[10px] font-bold text-muted uppercase tracking-widest mb-3">{t.filePreview.tags}</h4>
              <div className="flex flex-wrap gap-2">
                {tags.map(tag => (
                  <span key={tag} className="group px-3 py-1 bg-[#e5eeff] dark:bg-blue-950/40 hover:bg-blue-100 dark:hover:bg-blue-900/40 text-[#2563eb] dark:text-blue-400 text-xs font-medium rounded-full flex items-center gap-1.5 cursor-default transition-colors">
                    {tag}
                    <button onClick={() => handleRemoveTag(tag)} className="opacity-0 group-hover:opacity-100 hover:text-blue-800 dark:hover:text-blue-200 transition-opacity focus:opacity-100 outline-none">
                      <X className="size-3" />
                    </button>
                  </span>
                ))}
                {isAddingTag ? (
                  <input
                    type="text"
                    value={newTag}
                    onChange={(e) => setNewTag(e.target.value)}
                    onKeyDown={handleAddTag}
                    onBlur={() => {
                      setNewTag('')
                      setIsAddingTag(false)
                    }}
                    autoFocus
                    className="px-3 py-1 text-xs border border-blue-200 dark:border-blue-900/50 rounded-full focus:outline-none focus:border-[#2563eb] dark:focus:border-blue-500 w-24 bg-white dark:bg-slate-800 text-foreground"
                    placeholder={t.filePreview.newTagPlaceholder}
                  />
                ) : (
                  <button 
                    onClick={() => setIsAddingTag(true)}
                    className="px-3 py-1 border border-dashed border-slate-300 dark:border-slate-700 hover:border-[#2563eb] dark:hover:border-blue-500 text-muted hover:text-[#2563eb] dark:hover:text-blue-400 text-xs font-medium rounded-full flex items-center gap-1 transition-colors outline-none"
                  >
                    <Plus className="size-3" /> {t.filePreview.addTag}
                  </button>
                )}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Modal
        isOpen={isShareModalOpen}
        onClose={() => setIsShareModalOpen(false)}
        title={t.filePreview.shareAccess}
        description={t.filePreview.shareModalDesc}
        className="max-w-md"
      >
        <div className="flex flex-col gap-4 mt-2">
          {/* Link Section */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">{t.filePreview.shareLink}</label>
            <div className="flex items-center gap-2">
              <input 
                type="text" 
                readOnly 
                value={shareLinkValue} 
                className="flex-1 h-10 px-3 py-2 text-sm rounded-lg border border-border bg-slate-50 text-slate-500 focus:outline-none"
              />
              <Button 
                onClick={() => {
                  navigator.clipboard.writeText(shareLinkValue)
                  setIsLinkCopied(true);
                  setTimeout(() => setIsLinkCopied(false), 2000);
                }}
                className={`shrink-0 h-10 transition-colors ${
                  isLinkCopied 
                    ? 'bg-emerald-600 hover:bg-emerald-700 text-white' 
                    : 'bg-[#3155F6] hover:bg-[#2563eb] text-white'
                }`}
              >
                {isLinkCopied ? <Check className="size-4 mr-1.5" /> : <Share2 className="size-4 mr-1.5" />}
                {isLinkCopied ? t.filePreview.copied : t.filePreview.copy}
              </Button>
            </div>
            <p className="text-xs text-muted">{t.filePreview.shareLinkDesc}</p>
          </div>

          <div className="h-px bg-border my-2"></div>

          {/* Access List */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-foreground">{t.filePreview.peopleWithAccess}</label>
            
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Avatar src="/logo.png" name="Me" className="size-10" />
                <div>
                  <p className="text-[15px] font-bold text-slate-900">{t.filePreview.you}</p>
                  <p className="text-sm text-slate-500">alex.rivera@example.com</p>
                </div>
              </div>
              <span className="text-sm font-medium text-slate-500 pr-2">{t.sharedFolder.owner}</span>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="size-10 rounded-full bg-[#eff6ff] text-[#3155F6] flex items-center justify-center text-sm font-bold shadow-sm border border-[#dbeafe]">
                  SG
                </div>
                <div>
                  <p className="text-[15px] font-bold text-slate-900">Study Group Alpha</p>
                  <p className="text-sm text-slate-500">3 members</p>
                </div>
              </div>
              <div className="relative group">
                <select className="appearance-none w-24 h-[34px] pl-3 pr-8 bg-[#f8fafc] hover:bg-slate-100 border border-slate-200 text-slate-700 text-[13px] font-medium rounded-lg focus:outline-none focus:border-[#3155F6] focus:ring-1 focus:ring-[#3155F6] cursor-pointer transition-colors">
                  <option>{t.filePreview.viewer}</option>
                  <option selected>{t.filePreview.editor}</option>
                  <option>{t.filePreview.remove}</option>
                </select>
                <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 size-4 text-slate-500 pointer-events-none group-hover:text-slate-700 transition-colors" />
              </div>
            </div>
          </div>
        </div>
      </Modal>
    </div>
  )
}
