spring.application.name=lumiedu

spring.datasource.url=jdbc:mysql://localhost:3306/lumiedu?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080



momo.partner-code=MOMOBKUN20180529
momo.access-key=klm05TvNBzhg7h7j
momo.secret-key=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
momo.pay-url=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect-url=http://localhost:8080/api/billing/momo-callback
momo.ipn-url=http://localhost:8080/api/billing/momo-callback
